services:
  cis_backend_server:
    image: cis_backend_server:latest
    container_name: cis_backend_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080

  nginx:
    image: nginx:mainline-alpine
    hostname: nginx
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:14.2
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Jad108fsdlknzc"
    volumes:
      - pg_storage:/var/lib/postgresql/data
    ports:
      - 5436:5432

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    expose:
      - 9000
      - 9001
    volumes:
      - data1-1:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pg_storage:
  data1-1:
